- modules/ace_medical/params.hpp
To better meet the needs of The Bear Cave community, ACE revive should be defaulted to OFF (still allowable to switch it to ON at the mission maker's discretion).
> Update: ACE revive defaulted to OFF.

- modules/acre_setup/settings.sqf
I believe this is a wise thing to do and has been previously requested by mission makers and hence was implemented in my fork of the framework.
> Update: Default ACRE scramble to true.

- customization/loadouts.sqf
Adds Cake's request changes to loadouts.sqf so people who don't know how to write #include can make missions
- Adds commented out includes for default gearscripts
> Add commented #includes to loadouts.sqf

- modules/anti_nd/functions/anti_nd/fn_Init.sqf
- modules/anti_nd/preinitClient.sqf
- Fix the anti nd module.
There were 3 issues:
- The settings file wasn't being included so none of the settings variables were setup and therefore effectively ignored
- The logic to remove the fired event handler was not checking a case where a time setting was active but the distance setting disabled
- The logic to remove the fired event handler had the distance logic round the wrong way (checking for if the player was within the distance set, not outside of it, to remove the event handler)
> Fix for Anti ND module

- modules/ai_drivers/functions/AiDrivers/fn_AD_Init.sqf
- modules/ai_drivers/postInitClient.sqf
- modules/ai_drivers/preinitClient.sqf
- modules/ai_drivers/root.sqf
- modules/ai_drivers/settings.sqf
- Fix the AI drivers module
Reported by @goosko bug #37.
The list of specific vehicles to add driver AI on wasn't being used, also because there was no wait until the vehicles were even created in the game none of the other options would work.
> Fix for AI Drivers module

- core/functions/spectator/fn_startSpectator.sqf
- Use the correct ACRE (babel) variables when setting up spectator.
- Call hideObjectGlobal via the server, stops players appearing at the position of their body when playing in MP.
> Fix: Sectator fixes

- modules/modules.sqf
- modules/tracking_markers/functions/CfgFunctions.hpp
- modules/tracking_markers/functions/TRKMRKS/fn_trackMarker.sqf
- modules/tracking_markers/functions/TRKMRKS/fn_untrackMarker.sqf
- modules/tracking_markers/functions/TRKMRKS/script_component.hpp
- modules/tracking_markers/postInitServer.sqf
- modules/tracking_markers/preInitClient.sqf
- modules/tracking_markers/root.sqf
- modules/tracking_markers/script_component.hpp
- modules/tracking_markers/settings.sqf
- Adds a new "Tracking Markers" module which allows mission makers to setup markers to track specific objects or units and specify how often this updates on the map. Useful for HVT missions or a moving objective etc.
> Tracking markers module

- modules/anti_nd/functions/anti_nd/fn_Init.sqf
- changed to ACE action EH method
- disables firing and advanced throwing prompts, does not require magazine/ammo handling
> changed Anti ND method

- modules/headless_ai/cfgFunctions/Get/fn_getBuildings.sqf
adds in an additional check for hidden buildings
> exclude hidden buildings from buildingSearch

- modules/acre_setup/functions/ACRESetup/fn_ACRES_ClientInit.sqf
- modules/acre_setup/postInitClient.sqf
- modules/acre_setup/preInitClient.sqf
- modules/acre_setup/root.sqf
- Fix the issue of (when babel is enabled) players not being able to hear team mates set to a different language while spectating. I believe this was happening due to the ACRE client init running again overwriting the spectator script assigning them all the babel languages.
- Bug reported here: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/issues/130
> Fix: Babel languages in spectator

- core/functions/spectator/fn_startSpectator.sqf
- Due to the slightly different mechanism of checking for who killed the player when they die and enter spectator, it would never draw an icon at the position they died. Changed this to mimic same behaviour on the old framework.
> Update: Draw an icon where the player died, for the killcam.

- core/postInitClient.sqf
Also checks for player == ace_medical_lastDamageSource in case of bleed out death
> Include check for player == lastdamagesource

- modules/firemission/functions/FIREMIS/fn_FIREMIS_GetPointFiremissionText.sqf
- modules/firemission/functions/FIREMIS/fn_FIREMIS_InternalSpottingFiremission.sqf
- modules/firemission/preInitClient.sqf
- Fix an issue discovered when testing some custom random mortar firing with TheLocalPub. Basically, although several functions are supposed to support passing a marker name to them as a target, this wasn't supported by the code itself. I've fixed this and we've tested it with his mission.
> Fix: FIREMISSION - Allow markers to be targetted

- modules/anti_nd/functions/anti_nd/fn_Init.sqf
- modules/anti_nd/preinitClient.sqf
Automatically empties vehicle turret ammo while entering turret (ace safety was too slow sometimes and would allow for some rounds to go off before being safe) magazine is emptied and new full magazine is added to vehicle loadout. 
Disables vanilla throw and ace explosives while in timeout/area
> Anti ND Vehicle Turret Fix

- core/functions/fn_gearScript.sqf
- customization/gearSettings.sqf
- Missing gear setting to remove all gear which should be enabled by default, also when it was trying to remove the gear it wasn't passing a unit to the function so even though it was calling it, it wasn't providing a unit to call it on.
> Missing gearSetting for removeAllGear.

- modules/headless_ai/cfgFunctions/task/fn_taskAssign.sqf
Makes the PatrolDistance setting affect the default patrolling radius of groups with no task (default to Patrol)
> Default patrol distance setting

- description.ext
- modules/headless_ai/cfgFunctions/GetInfo/fn_getDetailsVehicleEmpty.sqf
- modules/headless_ai/cfgFunctions/GetInfo/fn_getSyncedObjects.sqf
- modules/headless_ai/cfgFunctions/create/fn_createEmptyVehicle.sqf
- modules/headless_ai/cfgFunctions/create/fn_createVehicle.sqf
- modules/headless_ai/root.sqf
- remove vehcrew from empty vehicle
- pushbackUnique vehicle pushback
- move statemachines and other fnc in config to description_other header 
- vehGearScript call fix
-  fix duplicate params in emptyVehicle fnc
> Fix preprecessor macros, empty vehicle param order

- modules/anti_nd/functions/anti_nd/fn_Init.sqf
- modules/anti_nd/preinitClient.sqf
- modules/anti_nd/settings.hpp
- option to disable quick throw (grenade throw button) in a mission
- still allows for ACE advanced throwing, only affects vanilla quick throw
- `disableQuickGrenades` setting in `modules\anti_nd\settings.hpp`, default is true (disabled quick throw)
> anti nd module option to disable quick throwing for the mission

- core/CfgFunctions.hpp
- core/functions/fn_softEndMission.sqf
- customization/endConditions.sqf
Missions can be "soft" ended via the FUNC(SoftEndMission) function.
The mission end warn message will display first, then count down the time to end, then display
the regular endmission screen. Minimum time to wait is 5 seconds. If no warn message is given, eg:
```sqf
["USMC VICTORY<br />VDV has retreated due to casualties.", "", 30] call FUNC(SoftEndMission);
```
then function uses the regular end mission text as the warn message as well.
```sqf
[
<MISSION END MESSAGE: STRING>, 
<MISSION END WARN MESSAGE: STRING | OPTIONAL>, 
<TIME TO WAIT: NUMBER | OPTIONAL>
] call FUNC(SoftEndMission);
```
eg. 
```sqf
["USMC VICTORY<br />VDV has retreated due to casualties.", "USMC VICTORY", 30] call FUNC(SoftEndMission);
```
Closes #231
> soft Mission End

- core/functions/fn_softEndMission.sqf
- customization/endConditions.sqf
- soft end with just message for GM ending 
If you want the mission to only display the end mission, and for it only to end when a GM calls it, set the time to wait to -1
eg. `["USMC VICTORY<br />VDV has retreated due to casualties.", "USMC VICTORY", -1] call FUNC(SoftEndMission);`
> soft end with just message for GM ending

- modules/headless_ai/functions/Diag/fn_checkView.sqf
- Test height is now added to the unit's Z position from getPosATL, making function work correctly for units in buildings or other elevation
- Target position is now eyePos instead of getPosASL, so grass & microterrain will be less of a factor for standing/crouching targets
> minor fixes to checkView

- modules/headless_ai/functions/Main/fn_initMain.sqf
Another small one. Initial random spawns would sometimes select the same element twice, resulting in one fewer than intended random spawns due to pushBackUnique being used here.
This fix uses deleteRange since Array subtraction apparently doesn't modify the original array in sqf, and also removes the weighting in addition to the selection.
> fixed initialRandomSpawns sometimes selecting same element twice

- modules/headless_ai/functions/CfgFunctions.hpp
- modules/headless_ai/functions/Combat/fn_CombatAssaultVehicle.sqf
- modules/headless_ai/functions/Combat/fn_CombatAttack.sqf
- modules/headless_ai/functions/Combat/fn_CombatBound.sqf
- modules/headless_ai/functions/create/fn_createSubGroup.sqf
- modules/headless_ai/functions/create/fn_finishGroupSpawn.sqf
- modules/headless_ai/functions/task/fn_taskAssault.sqf
- modules/headless_ai/functions/task/fn_taskAttack.sqf
- modules/headless_ai/functions/task/fn_taskRetreat.sqf
Think this addresses what you mentioned on discord, making the retreat stuff reusable in proper commander AI
- CombatAssault renamed to CombatBound
- Renamed assaultEngageDistance to engageDistance, consistent with use in other tasks
- Retreat is now its own task for future use in commander AI, pretty much the same as the assault task
- nextTask param in the assault & retreat tasks with sensible defaults. The CombatBound PFH no longer assigns the next task, it simply removes itself to indicate the bounding has ended, so scheduling next tasks is the tasks functions' responsibility
- fixed an edge case where if a subgroup was created which contained the original group's leader, the leader would not retain control over the original group upon rejoining
> refactor assault/retreat behaviour to use tasks more consistently in commanderAI

- modules/headless_ai/functions/Combat/fn_CombatDropOff.sqf
- modules/headless_ai/functions/Combat/fn_CombatLand.sqf
- Use the CombatLand function when a heli is given a dropoff task
- Copied the code from CombatDropoff to unload groups when a helicopter is landed, may be worth moving this to a shared CombatUnload function in the future
- Setting an rtbPos param will have the heli return to the specified position and land again after performing their dropoff task
To see this change in action, follow the helos from the north of the map: http://aar.globalconflicts.net/?file=2024_09_28__15_15_CO34AxetoFallv1.json&frame=831&zoom=4&x=-68.27083587646484&y=130.78122559249204
> use combatLand for aerial dropoff tasks
