- modules/modules.sqf
- modules/weapon_helper/cfgFunctions.hpp
- modules/weapon_helper/functions/fn_addMagazine.sqf
- modules/weapon_helper/functions/fn_addWeapon.sqf
- modules/weapon_helper/preinit.sqf
- modules/weapon_helper/root.sqf
- modules/weapon_helper/settings.sqf
> Added weapon_helper module

- core/functions/fn_briefing.sqf
- customization/briefings/changelog.sqf
This was requested by members of the community, encourages people to up-version their missions and describe what was changed between versions. Helps admins understand if previously known issues have been resolved etc..
> New: Changelog tab on briefings.

- core/description.hpp
- customization/missionAttributes.hpp
Update: Improved documentation of various description.hpp settings for 
mission makers.
> New: corpseManagerMode attribute added.

- modules/cover_map/functions/CoverMap/fn_CM_Live.sqf
- modules/cover_map/functions/CoverMap/fn_CM_bordersToMap.sqf
- modules/cover_map/preinitClient.sqf
- modules/cover_map/settings.sqf
Having tested this module re-write I think it would be a better idea to make the default cover map colour grey instead of black. I find black quite straining, grey is much more neutral and I think would be better for the majority of people. I've attached a comparison.
> Update: Default colour of the cover map changed from black to grey.

- modules/modules.sqf
- modules/remove_map/functions/CfgFunctions.hpp
- modules/remove_map/functions/RemoveMap/fn_RM_doRemoves.sqf
- modules/remove_map/functions/RemoveMap/script_component.hpp
- modules/remove_map/init.sqf
- modules/remove_map/postinitClient.sqf
- modules/remove_map/preinitClient.sqf
- modules/remove_map/root.sqf
- modules/remove_map/script_component.hpp
- modules/remove_map/settings.sqf
Updated the remove map module.
> Update: Remove map module now uses new format for modules.

- core/description.hpp
- Add the corpseManagerMode setting and a lot more detailed information regarding all of the options in the description.hpp file.
> Improve the description.hpp file

- modules/hostage/functions/HOST/fn_IsRescued.sqf
> change to GETVAR

- modules/modules.sqf
- modules/vehicle_boost/functions/CfgFunctions.hpp
- modules/vehicle_boost/functions/VEHBOOST/fn_VEHBOOST_Boost.sqf
- modules/vehicle_boost/functions/VEHBOOST/script_component.hpp
- modules/vehicle_boost/postInitClient.sqf
- modules/vehicle_boost/preInitClient.sqf
- modules/vehicle_boost/root.sqf
- modules/vehicle_boost/script_component.hpp
- modules/vehicle_boost/settings.sqf
- Add a new "Vehicle Boost" module to the framework which allows mission makers to specify specific vehicles as having a "BOOST" option set to their desired speed increase and cooldown.
> Vehicle boost module

- modules/ambient_animation/preinit.sqf
- Make the Ambient Animation module usable again.
> Fix: Functions were pointing to the wrong files in the Ambient Animation module.

- modules/ao_limit/init.sqf
- modules/ao_limit_soft/init.sqf
- modules/marker_control/init.sqf
- modules/setup_timer/init.sqf
- Fix any modules which rely on detecting if an area marker exists with `markerType`.
> Modules using area markers fixed after ArmA update.

- modules/anti_nd/functions/anti_nd/fn_Init.sqf
- modules/anti_nd/preinitClient.sqf
- Fix the issue that the Anti ND module wasn't stopping grenades thrown with advanced throwing.
> Anti ND - Advanced throwing wasn't being stopped

- modules/start_text/postInitClient.sqf
- modules/start_text/preInitClient.sqf
- modules/start_text/root.sqf
- Fix a bug which would run the start text for every player whenever a JIP joined.
> Fix: Start text would run for every player whenever a JIP joined.

- core/functions/fn_briefing.sqf
- customization/briefings/adminNotes.sqf
- customization/enhanced_briefings/adminNotes.sqf
- Fix the fact that the changelog briefing tab doesn't display.
- Add an admin notes briefing tab.
> Fix: Briefing tabs

- core/script_macros.hpp
- modules/jip/functions/CfgFunctions.hpp
- modules/jip/functions/JIP/fn_JIP_ServerInit.sqf
- modules/jip/functions/JIP/fn_clientInit.sqf
- modules/jip/functions/JIP/fn_serverInit.sqf
- modules/jip/functions/JIP/script_component.hpp
- modules/jip/postInitClient.sqf
- modules/jip/preInitClient.sqf
- modules/jip/preInitServer.sqf
- modules/jip/root.sqf
- modules/jip/script_component.hpp
- modules/jip/teleportAction.sqf
- modules/jip/transportAction.sqf
- Fix the JIP module
- INVEHICLE logic was round the wrong way
- Clean up the JIP module.
> JIP module fixes

- modules/ai_drivers/functions/AiDrivers/fn_AD_EnableAIDriver.sqf
- modules/ai_drivers/functions/AiDrivers/fn_AD_Init.sqf
…ns conditions to never evaluate to true.
- Fix the AI Drivers module, issue pointed out by @goosko
> Fix: AI Drivers ACE actions not appearing

- modules/marker_control/functions/MRKCON/fn_MRKCON_Add.sqf
- Allow the marker control module to work with shape markers.
> Marker control module - Fix: Use markerShape for checking area markers.

- modules/cover_map/functions/CoverMap/fn_CM_Init.sqf
- modules/cover_map/settings.sqf
- Optimisations for the cover map module.
> Cover map minor improvement

- customization/loadouts/1989VDV.sqf
- customization/loadouts/2000MSV.sqf
- customization/loadouts/BAF.sqf
- customization/loadouts/RU.sqf
- customization/loadouts/RURiflePlatoon.sqf
- customization/loadouts/USMCRiflePlatoon.sqf
- Update the default loadouts to more accurately show how they should be called in the units' inits.
> Default loadouts update

- modules/ao_limit_soft/functions/SAOLIM/fn_init.sqf
- modules/ao_limit_soft/preInitClient.sqf
- Fix an issue where the module would effectively check AOs for every player whether or not it applied to their team.
> AO Soft Limit bug fix

- modules/modules.sqf
- modules/set_face/functions/CfgFunctions.hpp
- modules/set_face/functions/SETFCE/fn_setFace.sqf
- modules/set_face/functions/SETFCE/script_component.hpp
- modules/set_face/postInitClient.sqf
- modules/set_face/preInitClient.sqf
- modules/set_face/root.sqf
- modules/set_face/script_component.hpp
- modules/set_face/settings.sqf
- Port the set face module to the new format.
> Set face module port

- core/CfgFunctions.hpp
- core/functions/spectator/fn_EGSpectator.sqf
- core/functions/spectator/fn_freezeUnit.sqf
- core/functions/spectator/fn_initSpectateScreen.sqf
- core/functions/spectator/fn_startSpectator.sqf
- core/functions/spectator/fn_thawUnit.sqf
- Hopefully make it harder for players to move when spectating.
> Enhancements to try to ensure players can't move when spectating

- modules/firemission/functions/FIREMIS/fn_FIREMIS_PointFiremission.sqf
- modules/firemission/functions/FIREMIS/fn_FIREMIS_RegisterForwardObserver.sqf
- modules/firemission/preInitClient.sqf
- Allow headless client AI to be forward observers.
- Reported here: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/issues/114
> Firemission hc compatibility

- core/CfgFunctions.hpp
- core/functions/spectator/fn_handleComboBoxChange.sqf
- core/functions/spectator/fn_handleListChange.sqf
- core/functions/spectator/fn_initSpectateScreen.sqf
- core/functions/spectator/fn_spectatorBriefing.sqf
- core/preinitClient.sqf
- Reported here: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/issues/131
- Other fixes:
- Fix: Also display changelog in spectator briefing screen.
- Fix: UI layout of briefing screen improved.
> Update: Display all briefings in spectator briefing screen.

- modules/anti_nd/functions/anti_nd/fn_Init.sqf
- modules/anti_nd/preinitClient.sqf
- modules/anti_nd/settings.sqf
- Allow per team settings for anti nd
> Anti nd team settings

- modules/firemission/functions/CfgFunctions.hpp
- modules/firemission/functions/FIREMIS/fn_FIREMIS_DoConstantArtillery.sqf
- modules/firemission/settings.sqf
- Provides a function to make a battery fire constantly at a target.
> Firemission - Function to do constant artillery throughout the mission.

- modules/currency/CfgCurrency.hpp
- modules/currency/functions/CURRENCY/fn_addCurrency.sqf
- modules/currency/functions/CURRENCY/fn_deductCurrency.sqf
- modules/currency/functions/CURRENCY/fn_getCurrency.sqf
- modules/currency/functions/CURRENCY/fn_getCurrencyText.sqf
- modules/currency/functions/CURRENCY/fn_setCurrency.sqf
- modules/currency/functions/CURRENCY/script_component.hpp
- modules/currency/functions/CfgFunctions.hpp
- modules/currency/preInitClient.sqf
- modules/currency/root.sqf
- modules/currency/script_component.hpp
- modules/currency/settings.sqf
- modules/modules.sqf
- Adds a brand new currency module, requested by @TheLocalPub
> Currency module

- modules/capture_zone/functions/CAPZONE/fn_setCaptureZone.sqf
- modules/capture_zone/functions/CAPZONE/fn_setColours.sqf
- modules/capture_zone/postInitServer.sqf
- modules/capture_zone/preInitClient.sqf
- modules/capture_zone/settings.sqf
- Fix the capture zone module
- Set functions had no effect
- There was a recursive infinite loop when trying to use the "setColours" function.
> Fixes for Capture zone

- modules/capture_zone/functions/CAPZONE/fn_isCaptured.sqf
- modules/capture_zone/functions/CAPZONE/fn_setCaptureZone.sqf
- modules/capture_zone/postInitServer.sqf
- modules/capture_zone/preInitClient.sqf
- Previously the capture zone module was never going to work properly after the CBA XEH changes, many of the variables it relies on were out of scope, not being recorded and just overwritten everytime the PFH executed.
> Capture zone checking fixes.

- modules/ai_drivers/functions/AiDrivers/fn_createDriver.sqf
- modules/ai_drivers/postInitClient.sqf
- remove duplicates with allClass/specific class settings
- remoteExec setEffectiveCommander
> AI Driver Unique Settings, RemoteExec SetEffectiveCommander

- modules/in_game_brief/functions/IGBRIEF/fn_register.sqf
- modules/in_game_brief/functions/IGBRIEF/fn_setup.sqf
- modules/in_game_brief/preInitClient.sqf
- modules/in_game_brief/settings.sqf
- Requested by @ReddishRed here: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/issues/174
- Removes some of the complication of the IG Brief setup, uses setup markers instead of placing 3 game logics.
> IG Brief - Logics no longer need to be place

- core/CfgFunctions.hpp
- core/functions/fn_getCO.sqf
- core/postInitClient.sqf
- core/postInitServer.sqf
- core/preinitClient.sqf
- core/preinitServer.sqf
- customization/serverSettings.sqf
- stringtable.xml
- Chain of command is now determined by an array set by the mission maker or automatically by rank.
> Logic to determine chain of command.

- modules/weapon_helper/preInitClient.sqf
- modules/weapon_helper/settings.sqf
- As suggested by @ReddishRed default all sides to get weapon attachments.
> Update: Default attachment changes to 1 for all sides.

- modules/in_game_brief/functions/IGBRIEF/fn_beginTheMission.sqf
- modules/in_game_brief/functions/IGBRIEF/fn_missionConfirmedBlu.sqf
- modules/in_game_brief/functions/IGBRIEF/fn_missionConfirmedRed.sqf
- modules/in_game_brief/functions/IGBRIEF/fn_missionStarter.sqf
- modules/in_game_brief/functions/IGBRIEF/fn_register.sqf
- modules/in_game_brief/functions/IGBRIEF/fn_setup.sqf
- modules/in_game_brief/functions/IGBRIEF/fn_startTheMissionBlu.sqf
- modules/in_game_brief/functions/IGBRIEF/fn_startTheMissionRed.sqf
- modules/in_game_brief/postInitClient.sqf
- modules/in_game_brief/postInitServer.sqf
- modules/in_game_brief/preInitClient.sqf
- There were lots of locality issues here where it would only work in the editor, I think it should be OK now but please feel free to double check?
> IG Brief - Attempt to fix locality issues.

- modules/anti_nd/functions/anti_nd/fn_Init.sqf
- modules/anti_nd/preinitClient.sqf
- Address the issue reported here: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/issues/184
> Fix: Remove troublesome event handler in anti_nd

- modules/ai_drivers/postInitClient.sqf
- modules/ai_drivers/preinitClient.sqf
- Fix a bug where the `selectVehicles` setting wasn't working.
Reported by @Aphex123
> AI Drivers bug - settings weren't working.

- modules/weapon_helper/preInitClient.sqf
- modules/weapon_helper/settings.sqf
- Issue reported by @Reddish_Red
- Independents wouldn't have any attachments added to their weapons.
> WEPHELP: Attachments weren't being added for ind side

- modules/anti_nd/functions/anti_nd/fn_Init.sqf
- Additional logging when anti_nd event handlers are removed so to try and debug https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/issues/196
> Update: Additional logging when anti_nd event handlers are removed.

- modules/ai_tasks/functions/AITSK/fn_findTarget.sqf
- Additional check to ensure the side of a target is on an enemy side.
> Fix: ai_tasks don't include targets which are friendly to the side.

- core/functions/fn_eventKilled.sqf
- core/functions/fn_eventRespawned.sqf
- core/functions/fn_eventSpawned.sqf
- core/functions/fn_untrackUnit.sqf
- customization/serverSettings.hpp
- modules/modules.sqf
Adds in the tracked variable when a unit dies so that the total can be added to once respawn occurs.
> Respawn handling

- core/preinitServer.sqf
Fixes incorrect config path for end condition frequency value
> end condition frequency fix

- modules/headless_ai/functions/create/fn_spawnUnitsVehiclePFH.sqf
- modules/headless_ai/functions/set/fn_setAssignedVehicle.sqf
Fixes AI in vehicles spawning with PZAI.
> fix vehicle spawning on HC

- modules/ao_limit_soft/functions/SAOLIM/fn_addAOMarker.sqf
- modules/marker_control/functions/CfgFunctions.hpp
- modules/marker_control/functions/MRKCON/fn_Add.sqf
- modules/marker_control/functions/MRKCON/fn_AddLayer.sqf
- modules/marker_control/postinitClient.sqf
- modules/marker_control/preinitClient.sqf
- modules/marker_control/root.sqf
- modules/marker_control/script_component.hpp
- modules/marker_control/settings.sqf
- move to external functions
- add ability to use layers for multiple markers
- optimization on postInit function
- add ability to restrict markers to multiple sides (array)
- add addLayer function for layer marker contol
> Marker Control Optimizations

- .gitignore
- customization/loadouts.sqf
- customization/loadouts/2022_US_Army_Stryker.sqf
- Update gitignore so `.vscode` folder is not tracked
- Add a new loadout/ORBAT for a modern day US Army Rifle Platoon mounted in Strykers
- Add corresponding Vehicle gear
- Link to steam composition for ready to place platoon units
> Stryker platoon

- modules/ai_drivers/functions/AiDrivers/fn_enableAIDriver.sqf
- modules/ai_drivers/functions/AiDrivers/fn_getDriverOpticsPos.sqf
- modules/ai_drivers/functions/AiDrivers/fn_toggleDriverCam.sqf
- modules/ai_drivers/functions/CfgFunctions.hpp
- modules/ai_drivers/postInitClient.sqf
- modules/ai_drivers/preinitClient.sqf
- modules/ai_drivers/settings.hpp
- test mode to generate driver view positions
- caching of driver view positions for inherited classes
- config setting for vehicle class view positions
- setting for display sizes and positions
- toggle action between top/bottom displays
> Added AI Driver test mode, top and bottom display modes

- modules/jip/functions/JIP/fn_teleport.sqf
- modules/jip/postInitClient.sqf
- modules/jip/preInitClient.sqf
- JIP deny settings
- type setting
Closes #237
> JIP deny settings, type setting

- core/CfgFunctions.hpp
- core/description.hpp
- core/dia/briefingMenu/dia_briefingMenu.hpp
- core/dia/briefingMenu/fn_briefingMenu.sqf
- core/dia/gearMenu/dia_gearMenu.hpp
- core/dia/gearMenu/fn_gearMenu.sqf
- core/dia/rscdefinitions.hpp
- core/functions/fn_briefing.sqf
- core/functions/fn_gearScript.sqf
- core/postInitClient.sqf
- core/preinitClient.sqf
- core/preinitServer.sqf
- Test Mode action for logged in/voted in admins on test server
- Briefing test
- Gear type test
> Testing features

- .gitignore
> Updated git ignore file.

- modules/setup_timer/postInitClient.sqf
UAVs controlled by UAV terminals can no longer escape setup area boundaries
> feat: apply setup timer areas to drones
